export const BLOCKS = [
  { id: "grass", name: "Bloc d'Herbe", image: "/assets/grass.png", cost: 0 },
  { id: "dirt", name: "Bloc de Terre", image: "/assets/dirt.png", cost: 100 },
  { id: "stone", name: "Bloc de Pierre", image: "/assets/stone.png", cost: 200 },
  { id: "cobblestone", name: "Pierre Taillée", image: "/assets/cobblestone.png", cost: 300 },
  { id: "oak_log", name: "Bûche de Chêne", image: "/assets/oak_log.png", cost: 400 },
  { id: "sand", name: "Sable", image: "/assets/sand.png", cost: 500 },
  { id: "gravel", name: "Gravier", image: "/assets/gravel.png", cost: 600 },
  { id: "coal_ore", name: "Minerai de Charbon", image: "/assets/coal_ore.png", cost: 800 },
  { id: "iron_ore", name: "Minerai de Fer", image: "/assets/iron_ore.png", cost: 1000 },
  { id: "gold_ore", name: "Minerai d'Or", image: "/assets/gold_ore.png", cost: 1500 },
  { id: "redstone_ore", name: "Minerai de Redstone", image: "/assets/redstone_ore.png", cost: 2000 },
  { id: "lapis_ore", name: "Minerai de Lapis", image: "/assets/lapis_ore.png", cost: 2500 },
  { id: "diamond_ore", name: "Minerai de Diamant", image: "/assets/diamond_ore.png", cost: 3000 },
  { id: "emerald_ore", name: "Minerai d'Émeraude", image: "/assets/emerald_ore.png", cost: 3500 },
  { id: "obsidian", name: "Obsidienne", image: "/assets/obsidian.png", cost: 4000 },
  { id: "netherrack", name: "Roche du Nether", image: "/assets/netherrack.png", cost: 5000 },
  { id: "soul_sand", name: "Sable des Âmes", image: "/assets/soul_sand.png", cost: 6000 },
  { id: "glowstone", name: "Pierre Lumineuse", image: "/assets/glowstone.png", cost: 7000 },
  { id: "nether_quartz_ore", name: "Minerai de Quartz", image: "/assets/nether_quartz_ore.png", cost: 8000 },
  { id: "ancient_debris", name: "Débris Antiques", image: "/assets/ancient_debris.png", cost: 10000 },
  { id: "end_stone", name: "Pierre de l'End", image: "/assets/end_stone.png", cost: 12000 },
  { id: "purpur", name: "Bloc de Purpur", image: "/assets/purpur.png", cost: 15000 },
  { id: "prismarine", name: "Prismarine", image: "/assets/prismarine.png", cost: 18000 },
  { id: "sea_lantern", name: "Lanterne Marine", image: "/assets/sea_lantern.png", cost: 20000 },
  { id: "crying_obsidian", name: "Obsidienne Pleureuse", image: "/assets/crying_obsidian.png", cost: 25000 },
  { id: "netherite_block", name: "Bloc de Netherite", image: "/assets/netherite_block.png", cost: 30000 },
  { id: "beacon", name: "Balise", image: "/assets/beacon.png", cost: 35000 },
  { id: "dragon_egg", name: "Œuf de Dragon", image: "/assets/dragon_egg.png", cost: 40000 },
];
