
export const BLOCKS = [
  { id: "grass", name: "Bloc d'Herbe", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c7/Grass_Block.png", cost: 0 },
  { id: "dirt", name: "Bloc de Terre", image: "https://fr-minecraft.net/img/blocs2/003-terre.png", cost: 100 },
  { id: "stone", name: "Bloc de Pierre", image: "https://fr-minecraft.net/img/blocs2/004.png", cost: 200 },
  { id: "cobblestone", name: "Pierre Taillée", image: "https://fr-minecraft.net/img/blocs2/098-00.png", cost: 300 },
  { id: "oak_log", name: "Bûche de Chêne", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Oak_Log_%28UD%29_JE5_BE3.png", cost: 400 },
  { id: "sand", name: "Sable", image: "https://fr-minecraft.net/img/blocs2/012-sable.png", cost: 500 },
  { id: "gravel", name: "Gravier", image: "https://fr-minecraft.net/img/blocs2/013.png", cost: 600 },
  { id: "coal_ore", name: "Minerai de Charbon", image: "https://fr-minecraft.net/img/blocs2/ore_coal.png", cost: 800 },
  { id: "iron_ore", name: "Minerai de Fer", image: "https://fr-minecraft.net/img/blocs2/ore_iron.png", cost: 1000 },
  { id: "gold_ore", name: "Minerai d'Or", image: "https://fr-minecraft.net/img/blocs2/ore_gold.png", cost: 1500 },
  { id: "redstone_ore", name: "Minerai de Redstone", image: "https://fr-minecraft.net/img/blocs2/ore_redstone.png", cost: 2000 },
  { id: "lapis_ore", name: "Minerai de Lapis", image: "https://fr-minecraft.net/img/blocs2/ore_lapis_lazuli.png", cost: 2500 },
  { id: "diamond_ore", name: "Minerai de Diamant", image: "https://fr-minecraft.net/img/blocs2/ore_diamond.png", cost: 3000 },
  { id: "emerald_ore", name: "Minerai d'Émeraude", image: "https://fr-minecraft.net/img/blocs2/ore_emerald.png", cost: 3500 },
  { id: "obsidian", name: "Obsidienne", image: "https://fr-minecraft.net/img/blocs2/049-obsidienne.png", cost: 4000 },
  { id: "netherrack", name: "Roche du Nether", image: "https://fr-minecraft.net/img/blocs2/087-pierre%20sanguine.png", cost: 5000 },
  { id: "soul_sand", name: "Sable des Âmes", image: "https://fr-minecraft.net/img/blocs2/088-sable%20enfer.png", cost: 6000 },
  { id: "glowstone", name: "Pierre Lumineuse", image: "https://fr-minecraft.net/img/blocs2/089-roche%20lumineuse.png", cost: 7000 },
  { id: "nether_quartz_ore", name: "Minerai de Quartz", image: "https://fr-minecraft.net/img/blocs2/153.png", cost: 8000 },
  { id: "ancient_debris", name: "Débris Antiques", image: "https://fr-minecraft.net/img/blocs2/ancient_debris.png", cost: 10000 },
  { id: "end_stone", name: "Pierre de l'End", image: "https://fr-minecraft.net/img/blocs2/121.png", cost: 12000 },
  { id: "purpur", name: "Bloc de Purpur", image: "https://fr-minecraft.net/img/blocs2/201.png", cost: 15000 },
  { id: "prismarine", name: "Prismarine", image: "https://fr-minecraft.net/img/blocs2/168_00.gif", cost: 18000 },
  { id: "sea_lantern", name: "Lanterne Marine", image: "https://fr-minecraft.net/img/blocs/169.gif", cost: 20000 },
  { id: "crying_obsidian", name: "Obsidienne Pleureuse", image: "https://fr-minecraft.net/img/blocs2/obsidian_crying.png", cost: 25000 },
  { id: "netherite_block", name: "Bloc de Netherite", image: "https://fr-minecraft.net/img/blocs2/netherite_block.png", cost: 30000 },
  { id: "beacon", name: "Balise", image: "https://fr-minecraft.net/img/blocs2/138.png", cost: 35000 },
  { id: "dragon_egg", name: "Œuf de Dragon", image: "https://fr-minecraft.net/img/blocs/122.png", cost: 40000 },
  { id: "command_block", name: "Bloc de Commande", image: "https://fr-minecraft.net/img/blocs2/137.png", cost: 50000 },
  { id: "bedrock", name: "Bedrock", image: "https://fr-minecraft.net/img/blocs2/007-bedrock.png", cost: 100000 }
];
