
export const BLOCKS = [
  { id: "grass", name: "Bloc d'Herbe", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c7/Grass_Block.png", cost: 0 },
  { id: "dirt", name: "Bloc de Terre", image: "https://fr-minecraft.net/img/blocs2/003-terre.png", cost: 100 },
  { id: "stone", name: "Bloc de Pierre", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Stone.png", cost: 200 },
  { id: "cobblestone", name: "Pierre Taillée", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Cobblestone.png", cost: 300 },
  { id: "oak_log", name: "Bûche de Chêne", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Oak_Log_%28UD%29_JE5_BE3.png", cost: 400 },
  { id: "sand", name: "Sable", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4b/Sand_JE7_BE6.png", cost: 500 },
  { id: "gravel", name: "Gravier", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b1/Gravel_JE4_BE3.png", cost: 600 },
  { id: "coal_ore", name: "Minerai de Charbon", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f1/Coal_Ore_JE4.png", cost: 800 },
  { id: "iron_ore", name: "Minerai de Fer", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8d/Iron_Ore_JE7_BE4.png", cost: 1000 },
  { id: "gold_ore", name: "Minerai d'Or", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/18/Gold_Ore_JE7_BE4.png", cost: 1500 },
  { id: "redstone_ore", name: "Minerai de Redstone", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e2/Redstone_Ore_JE4_BE3.png", cost: 2000 },
  { id: "lapis_ore", name: "Minerai de Lapis", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/47/Lapis_Lazuli_Ore_JE4_BE3.png", cost: 2500 },
  { id: "diamond_ore", name: "Minerai de Diamant", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/97/Diamond_Ore_JE5_BE5.png", cost: 3000 },
  { id: "emerald_ore", name: "Minerai d'Émeraude", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8b/Emerald_Ore_JE4_BE3.png", cost: 3500 },
  { id: "obsidian", name: "Obsidienne", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/11/Obsidian.png", cost: 4000 },
  { id: "netherrack", name: "Roche du Nether", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4d/Netherrack_JE4_BE3.png", cost: 5000 },
  { id: "soul_sand", name: "Sable des Âmes", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9c/Soul_Sand_JE3_BE2.png", cost: 6000 },
  { id: "glowstone", name: "Pierre Lumineuse", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4b/Glowstone_JE3_BE3.png", cost: 7000 },
  { id: "nether_quartz_ore", name: "Minerai de Quartz", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Nether_Quartz_Ore_JE3_BE2.png", cost: 8000 },
  { id: "ancient_debris", name: "Débris Antiques", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/44/Ancient_Debris_JE1_BE1.png", cost: 10000 },
  { id: "end_stone", name: "Pierre de l'End", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e4/End_Stone_JE3_BE2.png", cost: 12000 },
  { id: "purpur", name: "Bloc de Purpur", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8d/Purpur_Block_JE3_BE2.png", cost: 15000 },
  { id: "prismarine", name: "Prismarine", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9c/Prismarine_JE3_BE3.png", cost: 18000 },
  { id: "sea_lantern", name: "Lanterne Marine", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/72/Sea_Lantern_JE2_BE2.png", cost: 20000 },
  { id: "crying_obsidian", name: "Obsidienne Pleureuse", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Crying_Obsidian_JE2_BE1.png", cost: 25000 },
  { id: "netherite_block", name: "Bloc de Netherite", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Netherite_Block_JE1_BE1.png", cost: 30000 },
  { id: "beacon", name: "Balise", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9e/Beacon_JE7.png", cost: 35000 },
  { id: "dragon_egg", name: "Œuf de Dragon", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/dd/Dragon_Egg_JE3.png", cost: 40000 },
  { id: "command_block", name: "Bloc de Commande", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c5/Command_Block_JE2_BE2.png", cost: 50000 },
  { id: "bedrock", name: "Bedrock", image: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4d/Bedrock_JE4_BE3.png", cost: 100000 }
];
