export const UPGRADES = [
  { id: 1, name: "Pioche en bois", baseCost: 10, multiplier: 0.1, icon: "🪓" },
  { id: 2, name: "Pioche en pierre", baseCost: 50, multiplier: 0.5, icon: "⛏️" },
  { id: 3, name: "Pioche en fer", baseCost: 200, multiplier: 2, icon: "🔨" },
  { id: 4, name: "Villageois Mineur", baseCost: 300, multiplier: 1.5, icon: "👨" },
  { id: 5, name: "Creeper Apprivoisé", baseCost: 400, multiplier: 2.5, icon: "🟢" },
  { id: 6, name: "Redstone Avancée", baseCost: 600, multiplier: 4, icon: "🔴" },
  { id: 7, name: "Machine à Miner", baseCost: 800, multiplier: 5, icon: "⚙️" },
  { id: 8, name: "Pioche en diamant", baseCost: 1000, multiplier: 10, icon: "💎" }, 
  { id: 9, name: "TNT Automatique", baseCost: 1500, multiplier: 8, icon: "💣" },
  { id: 10, name: "Beacon Minier", baseCost: 2000, multiplier: 12, icon: "🔆" },
  { id: 11, name: "Enderman Helper", baseCost: 2500, multiplier: 13, icon: "👾" },
  { id: 12, name: "Portail du Nether", baseCost: 3000, multiplier: 15, icon: "🌋" },
  { id: 13, name: "Pioche magique", baseCost: 5000, multiplier: 50, icon: "✨" },
  { id: 14, name: "Elytra Magique", baseCost: 7000, multiplier: 35, icon: "🦋" },
  { id: 15, name: "Totem d'Immortalité", baseCost: 8500, multiplier: 45, icon: "🏆" },
  { id: 16, name: "Dragon de l'End", baseCost: 10000, multiplier: 100, icon: "🐉" },
  { id: 17, name: "Wither Boss", baseCost: 12000, multiplier: 120, icon: "💀" },
  { id: 18, name: "Herobrine", baseCost: 15000, multiplier: 150, icon: "👻" },
  { id: 19, name: "Notch Bénédiction", baseCost: 20000, multiplier: 200, icon: "👑" },
  { id: 20, name: "Minecraft Univers", baseCost: 25000, multiplier: 250, icon: "🌍" },
  { id: 21, name: "Steve Légendaire", baseCost: 30000, multiplier: 300, icon: "🎮" },
  { id: 22, name: "Alex Mythique", baseCost: 35000, multiplier: 350, icon: "🎯" },
  { id: 23, name: "Bloc Command", baseCost: 50000, multiplier: 500, icon: "⌨️" }
];
